FPS=60
# external window width: for real monitor/display
EXTERNAL_WIDTH=1920
EXTERNAL_HEIGHT=1080
# internal window width: for entire game area
SCREEN_WIDTH=1920
SCREEN_HEIGHT=1080
# total stage width, should around 3 screens
WORLD_WIDTH=SCREEN_WIDTH*4
PLAYER_SCREEN_EDGE_MARGIN=80

# Classical Proportions (Artistic & Anatomical)
# Width-to-height ratio: 1:4 ratio
# Biacromial width: 46.25 cm
# Head height units: 2 full heads wide
# height: 185 cm, shoulder: 46.25cm
# height: 182 cm, shoulder: 45.5cm
# height: 180 cm, shoulder: 45cm
# PLAYER_NAKED_HEIGHT=185
# PLAYER_NAKED_WIDTH=47
# Since arcade is left/right facing,
# the width is wider than shoulder

# Important: feet alignment matters most.anchor by feet, not by image center.
# Across idle, walk, attack, hit, etc., 
# the player’s feet should land on the same baseline. 
PLAYER_W=128 # static left/right facing width
PLAYER_H=256
# collision box is centered on bottom
# COLLISION UNIT == UNIT_LENGTH == PIXEL_PER_GRID == player shoulder width
PLAYER_COLLISION_W = 100
PLAYER_COLLISION_H = 50

ENEMY_W=PLAYER_W
ENEMY_H=PLAYER_H
ENEMY_COLLISION_W = PLAYER_COLLISION_W
ENEMY_COLLISION_H = PLAYER_COLLISION_H

# walkable area height
LANE_TOP=600-PLAYER_H
LANE_BOTTOM = 1040-PLAYER_H

UI_FIRST_X=32
UI_FIRST_Y=32
UI_FONT_SIZE=36

# Design note for the overlay colors:
# blue  = collision/footprint box
# green = hurtbox
# red   = attack hitbox
# orange = counter-hurtbox / extended limb vulnerability
# yellow = active enemy attack timing indicator
# module import is the right choice for mutable runtime flags.
SHOW_COMBAT_BOXES=False
SHOW_EXIT_RECT=True

PLAYER_LIVES=3

######## hp max ########
PLAYER_MAX_HP=100
ENEMY_MAX_HP=int(PLAYER_MAX_HP*1)

ENEMY_SCORE_POINTS = 100

######## speed ########
SPEED_SCALER = 3
# 7
PLAYER_SPEED = 3.2 * SPEED_SCALER
PLAYER_RUN_SPEED= 6.5*5 #PLAYER_SPEED*2
RUN_DOUBLE_TAP_TIME=0.25
ATTACK_3_FORWARD_NUDGE_FRAMES=3
ATTACK_3_FORWARD_NUDGE_SPEED_SCALE=0.35
RUN_ATTACK_REQUIRED_DISTANCE=100
RUN_ATTACK_FULL_POWER_DISTANCE=240
RUN_ATTACK_MOMENTUM_FRAMES=18
RUN_ATTACK_MOMENTUM_SPEED_SCALE=0.85
RUN_ATTACK_LANDING_RECOVERY=4
RUN_ATTACK_BASE_KNOCKBACK=18
RUN_ATTACK_FULL_POWER_KNOCKBACK_BONUS=6
RUN_ATTACK_BASE_ENEMY_HIT_STUN=40
RUN_ATTACK_FULL_POWER_ENEMY_HIT_STUN_BONUS=6

ENEMY_SPEED=2.0 * SPEED_SCALER
RAPTOR_ENEMY_SPEED=ENEMY_SPEED*1.3
BOSS_ENEMY_SPEED=ENEMY_SPEED*0.5
PROJECTILE_SPEED=ENEMY_SPEED*4
BOSS_SPECIAL_ATTACK_WARNING_DURATION=45

######## ranges ########
PLAYER_GRAB_RANGE = int(PLAYER_W * 0.4)
ENEMY_DETECT_RANGE=SCREEN_WIDTH*0.50

######## enemy attack timing ########
ENEMY_ATTACK_RANGE=130
ENEMY_ATTACK_LANE_RANGE=50

# windup:prepare -> active attack (hit player once) 
# -> recovery (enemy cannot move)->cooldown(frame cooldown before next attack)
ENEMY_ATTACK_DELAY=10

ENEMY_ATTACK_WINDUP=10 
ENEMY_ATTACK_ACTIVE=4
ENEMY_ATTACK_RECOVERY=6

ENEMY_ATTACK_COOLDOWN=20
ENEMY_ATTACK_CLASH_RECOVERY_DURATION=6
ENEMY_ATTACK_CLASH_COOLDOWN_DURATION=10
# Only a small number of regular melee enemies should enter ATTACK at the same time.
MAX_MELEE_ATTACKERS = 4
ENEMY_FLANK_OFFSET_X = 120
# avoid multiple enemies stack on the same lane. 
# give flankers a small Y offset based on crowding.
ENEMY_FLANK_OFFSET_Y = 36
ENEMY_FLANK_DECISION_DURATION = 45
ENEMY_FLANK_Y_TOLERANCE = 18

####################################
# ATTACK
FIST_DAMAGE=10
ATTACK_1_DAMAGE=10
ATTACK_1__HIT_STUN=10
ATTACK_1_WINDUP_DURATION=3
ATTACK_1_ACTIVE_DURATION=3
ATTACK_1__RECOVERY_DURATION=5

ATTACK_2_DAMAGE=12
ATTACK_2__HIT_STUN=10
ATTACK_2_WINDUP_DURATION=4
ATTACK_2_ACTIVE_DURATION=4
ATTACK_2__RECOVERY_DURATION=6

ATTACK_3_DAMAGE=15
ATTACK_3__HIT_STUN=10
ATTACK_3_WINDUP_DURATION=5
ATTACK_3_ACTIVE_DURATION=4
ATTACK_3__RECOVERY_DURATION=8

ATTACK_4_DAMAGE=20
ATTACK_4__HIT_STUN=15
ATTACK_4_WINDUP_DURATION=6
ATTACK_4_ACTIVE_DURATION=6
ATTACK_4__RECOVERY_DURATION=12

ATTACK_4_DAMAGE=35
# RUN ATTACK
RUN_ATTACK_DAMAGE=28
RUN_ATTACK_HIT_STUN=15
RUN_ATTACK_WINDUP_DURATION=4
RUN_ATTACK_ACTIVE_DURATION=16
RUN_ATTACK_RECOVERY_DURATION=6
RUN_ATTACK_TOTAL_DURATION=26


KNIFE_DAMAGE=int(FIST_DAMAGE*1.5)
BAT_DAMAGE=int(FIST_DAMAGE*2)
THROWN_DAMAGE=int(FIST_DAMAGE*1.5)
######## grab combo ########
PLAYER_GRAB_KNEE_DURATION = 14
PLAYER_GRAB_KNEE_HIT_FRAME = 6
# range weapons
PISTOL_DAMAGE=int(FIST_DAMAGE*3)

# enemies attack damage
ENEMY_ATTACK_DAMAGE=FIST_DAMAGE
RANGED_ENEMY_ATTACK_DAMAGE=ENEMY_ATTACK_DAMAGE*0.5
RAPTOR_ENEMY_ATTACK_DAMAGE=ENEMY_ATTACK_DAMAGE*1.2


