SCREEN_WIDTH=1000
SCREEN_HEIGHT=600
WORLD_WIDTH=3000
WORLD_HEIGHT=600
FPS=60

LANE_TOP=50
LANE_BOTTOM=500

SHOW_PLAYER_RECT=True
SHOW_PLAYER_HITBOX=True
SHOW_ENEMY_RECT=False
SHOW_ENEMY_HITBOX=True

PLAYER_LIVES=3

######## sizes ########
PLAYER_W=60
PLAYER_H=80
NORMAL_ENEMY_W=50
NORMAL_ENEMY_H=70
FAST_ENEMY_W=50
FAST_ENEMY_H=60
HEAVY_ENEMY_W=80
HEAVY_ENEMY_H=100
BOSS_ENEMY_W=150
BOSS_ENEMY_H=300

######## hit boxes ########
PLAYER_HITBOX_W=55
PLAYER_HITBOX_H=55
PLAYER_HITBOX_OFFSET_X=0
PLAYER_HITBOX_OFFSET_Y=10

PLAYER_GRAB_RANGE=70

ENEMY_HITBOX_W=50
ENEMY_HITBOX_OFFSET_W=50
ENEMY_HITBOX_OFFSET_H=50
BOSS_ENEMY_HITBOX_W=80
BOSS_ENEMY_HITBOX_H=80

######## hp max ########
PLAYER_MAX_HP=100
NORMAL_ENEMY_MAX_HP=60
FAST_ENEMY_MAX_HP=50
HEAVY_ENEMY_MAX_HP=120
BOSS_ENEMY_MAX_HP=800

######## speed ########
PLAYER_SPEED=5
NORMAL_ENEMY_SPEED=3
FAST_ENEMY_SPEED=6
HEAVY_ENEMY_SPEED=2
BOSS_ENEMY_SPEED=2

######## damages ########
# player attack damage
# melee weapons
FIST_DAMAGE=20
KNIFE_DAMAGE=25
BAT_DAMAGE=30
THROWN_DAMAGE=40
# range weapons
PISTOL_DAMAGE=15

# enemies attack damage
NORMAL_ENEMY_ATTACK_DAMAGE=15
FAST_ENEMY_ATTACK_DAMAGE=10
HEAVY_ENEMY_ATTACK_DAMAGE=25
BOSS_ENEMY_ATTACK_DAMAGE=30




