EPISODE_1_STAGES = [
    {
        "id": "episode_1_stage_1_rooftop",
        "name": "Rooftop Approach",
        "background": "assets/backgrounds/episode_1/episode_1_stage_1_rooftop.png",
        "world_width": 3338,
        "world_height": 1080,
        "player_start": (160, 620),
        "lane_top": 520,
        "lane_bottom": 830,
        "waves": [
            {
                "trigger_x": 900,
                "max_active": 2,
                "spawns": [
                    {
                        "enemy_type": "ferris",
                        "count": 2
                    }
                ],
            },
            {
                "trigger_x": 1600,
                "max_active": 2,
                "spawns": [
                    {
                        "enemy_type": "ferris",
                    },
                    {
                        "enemy_type": "gneiss",
                        "side": "left",
                    }
                ],
            },
            {
                "trigger_x": 2700,
                "max_active": 3,
                "spawns": [
                    {
                        "enemy_type": "gneiss",
                        "count": 2,
                    },
                    {
                        "enemy_type": "black_elmer",
                        "side": "left",
                    },
                ],
            },
        ],
        "weapons": [
            #{"type": "knife", "x": 850, "y": 600},
            #{"type": "bat", "x": 1750, "y": 600},
            #{"type": "pistol", "x": 2260, "y": 760},
        ],
        "objects": [
            #{"kind": "breakable", "x": 880, "y": 500},
            {"kind": "breakable", "x": 1780, "y": 500},
            #{"kind": "barrel", "x": 1740, "y": 760},
            #{"kind": "breakable", "x": 2320, "y": 760},
        ],
        "completion": "clear_waves_then_exit",
        "exit_rect": (2700, 340, 100, 260),
    },
    {
        "id": "episode_1_stage_2_hallway",
        "name": "Mansion Hallway",
        "background": "assets/backgrounds/episode_1/episode_1_stage_2_hallway.png",
        "world_width": 3132,
        "world_height": 1080,
        "player_start": (160, 720),
        "lane_top": 650,
        "lane_bottom": 1080,
        "waves": [
            {
                "trigger_x": 900,
                "max_active": 3,
                "spawns": [
                    {
                        "enemy_type": "ferris",
                        "side": "right",
                        "delay_min": 40,
                        "delay_max": 80,
                        "y_min": 720,
                        "y_max": 900,
                    },
                    {
                        "enemy_type": "ferris",
                        "side": "right",
                        "delay_min": 70,
                        "delay_max": 120,
                        "y_min": 820,
                        "y_max": 1020,
                    },
                    {
                        "enemy_type": "ferris",
                        "side": "left",
                        "delay_min": 100,
                        "delay_max": 150,
                        "y_min": 700,
                        "y_max": 960,
                    },
                ],
            },
            {
                "trigger_x": 1800,
                "max_active": 3,
                "spawns": [
                    {
                        "enemy_type": "ferris",
                        "side": "right",
                        "delay_min": 50,
                        "delay_max": 90,
                        "y_min": 720,
                        "y_max": 980,
                    },
                    {
                        "enemy_type": "gneiss",
                        "side": "left",
                        "delay_min": 90,
                        "delay_max": 140,
                        "y_min": 680,
                        "y_max": 900,
                    },
                    {
                        "enemy_type": "gneiss",
                        "side": "right",
                        "delay_min": 130,
                        "delay_max": 190,
                        "y_min": 820,
                        "y_max": 1040,
                    },
                ],
            },
            {
                "trigger_x": 2250,
                "max_active": 4,
                "spawns": [
                    {
                        "enemy_type": "ferris",
                        "count": 3,
                        "side": "right",
                        "delay_min": 80,
                        "delay_max": 130,
                        "y_min": 720,
                        "y_max": 1040,
                    },
                    {
                        "enemy_type": "black_elmer",
                        "count": 2,
                        "side": "left",
                        "delay_min": 130,
                        "delay_max": 210,
                        "y_min": 700,
                        "y_max": 980,
                        "enter_offset": 140,
                    },
                ],
            },
        ],
        "weapons": [
            {"type": "knife", "x": 850, "y": 760},
            #{"type": "bat", "x": 1750, "y": 760},
            #{"type": "pistol", "x": 2220, "y": 760},
        ],
        "objects": [
            #{"kind": "breakable", "x": 880, "y": 760},
            {"kind": "breakable", "x": 1780, "y": 760},
            #{"kind": "barrel", "x": 1740, "y": 760},
            #{"kind": "breakable", "x": 2280, "y": 760},
        ],
        "completion": "clear_waves_then_exit",
        "exit_rect": (2800, 650, 150, 420),
    },
    {
        "id": "episode_1_stage_3_transition",
        "name": "Ruined Building",
        "background": "assets/backgrounds/episode_1/episode_1_stage_3_transition.png",
        "world_width": 652,
        "world_height": 1080,
        "player_start": (120, 790),
        "lane_top": 760,
        "lane_bottom": 1080,
        "waves": [],
        "weapons": [],
        "objects": [],
        "completion": "reach_exit",
        "exit_rect": (900, 760, 120, 320),
    },
    {
        "id": "episode_1_stage_4_ruined_arena",
        "name": "Ruined Arena",
        "background": "assets/backgrounds/episode_1/episode_1_stage_4_ruined_arena.png",
        "world_width": 3086,
        "world_height": 1080,
        "player_start": (160, 720),
        "lane_top": 620,
        "lane_bottom": 1080,
        "waves": [
            {
                "trigger_x": 900,
                "max_active": 3,
                "spawns": [
                    {
                        "enemy_type": "ferris",
                        "side": "right",
                        "delay_min": 40,
                        "delay_max": 90,
                        "y_min": 700,
                        "y_max": 940,
                    },
                    {
                        "enemy_type": "ferris",
                        "side": "right",
                        "delay_min": 80,
                        "delay_max": 130,
                        "y_min": 820,
                        "y_max": 1040,
                    },
                    {
                        "enemy_type": "ferris",
                        "side": "left",
                        "delay_min": 110,
                        "delay_max": 170,
                        "y_min": 660,
                        "y_max": 900,
                    },
                ],
            },
            {
                "trigger_x": 1700,
                "max_active": 3,
                "spawns": [
                    {
                        "enemy_type": "gneiss",
                        "side": "right",
                        "delay_min": 60,
                        "delay_max": 110,
                        "y_min": 700,
                        "y_max": 920,
                    },
                    {
                        "enemy_type": "gneiss",
                        "side": "left",
                        "delay_min": 100,
                        "delay_max": 160,
                        "y_min": 820,
                        "y_max": 1040,
                    },
                    {
                        "enemy_type": "black_elmer",
                        "side": "right",
                        "delay_min": 150,
                        "delay_max": 230,
                        "y_min": 720,
                        "y_max": 980,
                        "enter_offset": 140,
                    },
                ],
            },
            {
                "kind": "boss",
                "trigger_x": 2250,
            },
        ],
        "weapons": [
            {"type": "knife", "x": 850, "y": 760},
            {"type": "bat", "x": 1750, "y": 760},
            {"type": "pistol", "x": 2220, "y": 760},
        ],
        "objects": [
            {"kind": "breakable", "x": 880, "y": 760},
            {"kind": "breakable", "x": 1780, "y": 760},
            {"kind": "barrel", "x": 1740, "y": 760},
            {"kind": "breakable", "x": 2280, "y": 760},
        ],
        "completion": "clear_waves_then_exit",
        "exit_rect": (2500, 620, 140, 460),
    },
]
